version: "3.7"
services:
  app:
    build:
      args:
        user: maks
        uid: 1000
      context: ./
      dockerfile: Dockerfile
    image: travellist
    container_name: travellist-app
    restart: unless-stopped
    working_dir: /var/www/
    volumes:
      - ./:/var/www
    networks:
      - travellist

  db:
    image: mysql:5.7
    container_name: travellist-db
    restart: unless-stopped
    environment:
      MYSQL_DATABASE: travellist
      MYSQL_ROOT_PASSWORD: shehtman.mi
      MYSQL_PASSWORD: password
      MYSQL_USER: travellist_user
      SERVICE_TAGS: dev
      SERVICE_NAME: mysql
    volumes:
      - ./docker-compose/mysql/init_db.sql:/init_db.sql
    networks:
      - travellist

  nginx:
    image: nginx:alpine
    container_name: travellist-nginx
    restart: unless-stopped
    ports:
      - "8000:80"
    volumes:
      - ./:/var/www
      - ./docker-compose/nginx:/etc/nginx/conf.d/
    networks:
      - travellist
  appserver:
    image: 'angular-laravel-spa-site'
    container_name: laravel-spa-client-server
    # Build the image if don't exist
    build: './client'
    ports:
      - "3000:81"

networks:
  travellist:
    driver: bridge
